import { useEffect, useState } from 'react';
import { getAvailablePhones } from '../../services/phoneService';
import { borrowPhone, DEPARTMENTS, type Department } from '../../services/phoneTransactionService';
import { getLocalDateTime } from '../../lib/dateTime';
import { FeedbackMessage } from '../../components/FeedbackMessage';
import type { Phone } from '../../types/phone';
import type { AppUser } from '../../types/auth';
export default function BorrowPhone({ user, onBack }: { user: AppUser; onBack: () => void }) {
  const [phones, setPhones] = useState<Phone[]>([]); const [phoneId, setPhoneId] = useState(''); const [department, setDepartment] = useState<Department | ''>(''); const [date, setDate] = useState(''); const [time, setTime] = useState(''); const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null); const [saving, setSaving] = useState(false);
  const load = async () => { try { setPhones(await getAvailablePhones()); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Failed to load available phones.' }); } };
  useEffect(() => { const now = getLocalDateTime(); setDate(now.date); setTime(now.time); void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!phoneId || !department) { setMessage({ type: 'error', text: 'Select a phone and department.' }); return; } try { setSaving(true); await borrowPhone(Number(phoneId), date, time, user.username, department); setMessage({ type: 'success', text: 'Phone borrowed successfully.' }); window.setTimeout(onBack, 1200); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Failed to borrow phone.' }); await load(); } finally { setSaving(false); } };
  return <div className="app-page user-app-page">{message && <FeedbackMessage type={message.type} message={message.text} onClose={() => setMessage(null)} />}<header className="app-header"><div><h1>MELWIRE LANKA (PVT) LTD</h1><p>PHONE & CHARGER MANAGEMENT SYSTEM</p></div></header><main className="form-page user-form-page"><button className="back-button" onClick={onBack}>← Back to Dashboard</button><div className="form-card user-form-card"><h2>Borrow Phone</h2><p>Select a phone and record the borrowing details.</p>{phones.length === 0 ? <div className="empty-state">No phones are currently available.</div> : <form onSubmit={submit}><div className="form-group"><label>Available Phone</label><select value={phoneId} onChange={e => setPhoneId(e.target.value)} required><option value="">Select a phone</option>{phones.map(phone => <option key={phone.id} value={phone.id}>{phone.phone_identifier}</option>)}</select></div><div className="form-group"><label>Department</label><select value={department} onChange={e => setDepartment(e.target.value as Department)} required><option value="">Select department</option>{DEPARTMENTS.map(value => <option key={value} value={value}>{value}</option>)}</select></div><div className="form-row"><div className="form-group"><label>Date</label><input type="date" value={date} onChange={e => setDate(e.target.value)} required /></div><div className="form-group"><label>Time</label><input type="time" value={time} onChange={e => setTime(e.target.value)} required /></div></div><div className="form-group"><label>Borrowed By</label><div className="read-only-field">{user.username}</div></div><button className="primary-button full-width" disabled={saving}>{saving ? 'Processing...' : 'Confirm Borrowing'}</button></form>}</div></main></div>;
}
