import { useEffect, useState } from 'react';
import { getBorrowedPhones } from '../../services/phoneService';
import { returnPhone } from '../../services/phoneTransactionService';
import { getAdminUsers } from '../../services/authService';
import { getLocalDateTime } from '../../lib/dateTime';
import { FeedbackMessage } from '../../components/FeedbackMessage';
import type { Phone } from '../../types/phone';
import type { AppUser } from '../../types/auth';
export default function ReturnPhone({ user, onBack }: { user: AppUser; onBack: () => void }) {
  const [phones, setPhones] = useState<Phone[]>([]); const [admins, setAdmins] = useState<AppUser[]>([]); const [phoneId, setPhoneId] = useState(''); const [adminId, setAdminId] = useState(''); const [date, setDate] = useState(''); const [time, setTime] = useState(''); const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null); const [saving, setSaving] = useState(false);
  const load = async () => { try { setPhones(await getBorrowedPhones()); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Failed to load borrowed phones.' }); } };
  useEffect(() => { const now = getLocalDateTime(); setDate(now.date); setTime(now.time); void Promise.all([load(), getAdminUsers().then(setAdmins)]); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const admin = admins.find(item => String(item.user_id) === adminId); if (!phoneId || !admin) { setMessage({ type: 'error', text: 'Select a phone and receiving admin.' }); return; } try { setSaving(true); await returnPhone(Number(phoneId), date, time, admin.user_id, admin.username, user.username); setMessage({ type: 'success', text: 'Return submitted. Waiting for admin confirmation.' }); window.setTimeout(onBack, 1200); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Failed to return phone.' }); await load(); } finally { setSaving(false); } };
  return <div className="app-page user-app-page">{message && <FeedbackMessage type={message.type} message={message.text} onClose={() => setMessage(null)} />}<header className="app-header"><div><h1>MELWIRE LANKA (PVT) LTD</h1><p>PHONE & CHARGER MANAGEMENT SYSTEM</p></div></header><main className="form-page user-form-page"><button className="back-button" onClick={onBack}>← Back</button><div className="form-card user-form-card"><h2>Return Phone</h2><p>Select the phone and admin receiving it.</p>{phones.length === 0 ? <div className="empty-state">No phones are currently borrowed.</div> : <form onSubmit={submit}><div className="form-group"><label>Borrowed Phone</label><select value={phoneId} onChange={e => setPhoneId(e.target.value)} required><option value="">Select a phone</option>{phones.map(phone => <option key={phone.id} value={phone.id}>{phone.phone_identifier}</option>)}</select></div><div className="form-group"><label>Returned To</label><select value={adminId} onChange={e => setAdminId(e.target.value)} required><option value="">Select an admin</option>{admins.map(admin => <option key={admin.user_id} value={admin.user_id}>{admin.username}</option>)}</select></div><div className="form-row"><div className="form-group"><label>Date</label><input type="date" value={date} onChange={e => setDate(e.target.value)} required /></div><div className="form-group"><label>Time</label><input type="time" value={time} onChange={e => setTime(e.target.value)} required /></div></div><button className="primary-button full-width" disabled={saving}>{saving ? 'Processing...' : 'Confirm Return'}</button></form>}</div></main></div>;
}
