create table if not exists public.charger_damage_reports (
    id bigint generated by default as identity primary key,
    charger_id bigint not null references public.chargers(id) on delete cascade,
    damage_description text not null check (length(trim(damage_description)) > 0),
    repair_status text not null default 'pending'
        check (repair_status in ('pending', 'repaired')),
    reported_at timestamptz not null default now(),
    repaired_at timestamptz
);

create index if not exists charger_damage_reports_status_idx
    on public.charger_damage_reports (repair_status);

alter table public.charger_damage_reports enable row level security;

drop policy if exists "Allow charger damage report reads" on public.charger_damage_reports;
create policy "Allow charger damage report reads"
    on public.charger_damage_reports for select
    using (true);

drop policy if exists "Allow charger damage report inserts" on public.charger_damage_reports;
create policy "Allow charger damage report inserts"
    on public.charger_damage_reports for insert
    with check (true);

drop policy if exists "Allow charger damage report updates" on public.charger_damage_reports;
create policy "Allow charger damage report updates"
    on public.charger_damage_reports for update
    using (true)
    with check (true);

notify pgrst, 'reload schema';
