begin;

create extension if not exists pgcrypto;

create table if not exists public.app_users (
    user_id bigint generated by default as identity primary key,
    username text not null unique check (length(trim(username)) > 0),
    password_hash text not null,
    role text not null default 'user' check (role in ('admin', 'user')),
    created_at timestamptz not null default now()
);

create table if not exists public.it_team_members (
    id bigint generated by default as identity primary key,
    name text not null check (length(trim(name)) > 0),
    position text not null check (length(trim(position)) > 0),
    created_at timestamptz not null default now()
);

alter table public.charger_transactions
    add column if not exists returned_to_member_id bigint
        references public.it_team_members(id) on delete set null;

alter table public.app_users enable row level security;
alter table public.it_team_members enable row level security;

drop policy if exists "Allow app user inserts" on public.app_users;
create policy "Allow app user inserts" on public.app_users for insert with check (false);

drop policy if exists "Allow team member reads" on public.it_team_members;
create policy "Allow team member reads" on public.it_team_members for select using (true);

drop policy if exists "Allow team member inserts" on public.it_team_members;
create policy "Allow team member inserts" on public.it_team_members for insert with check (true);

create or replace function public.login_app_user(
    p_username text,
    p_password text
)
returns table(user_id bigint, username text, role text)
language sql
security definer
set search_path = public
as $$
    select u.user_id, u.username, u.role
    from public.app_users u
    where lower(u.username) = lower(trim(p_username))
      and u.password_hash = crypt(p_password, u.password_hash)
    limit 1;
$$;

drop function if exists public.create_app_user(text, text);

create function public.create_app_user(
    p_username text,
    p_password text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if length(trim(p_username)) = 0 or length(p_password) = 0 then
        raise exception 'Username and password are required.';
    end if;

    insert into public.app_users (username, password_hash, role)
    values (trim(p_username), crypt(p_password, gen_salt('bf')), 'user')
exception
    when unique_violation then
        raise exception 'That username already exists.';
end;
$$;

grant execute on function public.login_app_user(text, text) to anon, authenticated;
grant execute on function public.create_app_user(text, text) to anon, authenticated;

notify pgrst, 'reload schema';

commit;
