begin;

create table if not exists public.admins (
    id bigint generated by default as identity primary key,
    app_user_id bigint not null unique references public.app_users(id) on delete cascade,
    created_at timestamptz not null default now()
);

insert into public.admins (app_user_id)
select id
from public.app_users
where role = 'admin'
on conflict (app_user_id) do nothing;

alter table public.charger_transactions
    add column if not exists returned_by_username text,
    add column if not exists returned_to_admin_id bigint references public.app_users(id) on delete set null,
    add column if not exists approved_by_admin_id bigint references public.admins(id) on delete set null,
    add column if not exists approved_at timestamptz;

alter table public.admins enable row level security;
drop policy if exists "Allow admin reads" on public.admins;
create policy "Allow admin reads" on public.admins for select using (true);

create or replace function public.list_admin_users()
returns table(admin_id bigint, user_id bigint, username text)
language sql security definer set search_path = public
as $$
    select a.id, u.id as user_id, u.username
    from public.admins a
    join public.app_users u on u.id = a.app_user_id
    where u.role = 'admin'
    order by u.username;
$$;

create or replace function public.create_admin_user(p_username text, p_password text)
returns void
language plpgsql security definer set search_path = public
as $$
declare
    new_user_id bigint;
begin
    if length(trim(p_username)) = 0 or length(p_password) = 0 then
        raise exception 'Username and password are required.';
    end if;
    insert into public.app_users (username, password_hash, role, is_active)
    values (trim(p_username), extensions.crypt(p_password, extensions.gen_salt('bf')), 'admin', true)
    returning id into new_user_id;
    insert into public.admins (app_user_id) values (new_user_id);
exception
    when unique_violation then raise exception 'That username already exists.';
end;
$$;

create or replace function public.approve_charger_return(
    p_transaction_id bigint,
    p_admin_user_id bigint
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
    admin_record public.admins;
    transaction_record public.charger_transactions;
begin
    select a.* into admin_record
    from public.admins a
    join public.app_users u on u.id = a.app_user_id
    where u.id = p_admin_user_id and u.role = 'admin';
    if admin_record.id is null then raise exception 'Only an admin can approve returns.'; end if;

    select * into transaction_record
    from public.charger_transactions
    where id = p_transaction_id
      and status = 'return_pending'
      and returned_to_admin_id = p_admin_user_id
    for update;
    if transaction_record.id is null then raise exception 'This return is no longer pending.'; end if;

    update public.charger_transactions
    set status = 'returned', approved_by_admin_id = admin_record.id, approved_at = now()
    where id = p_transaction_id;
    update public.chargers set status = 'available'
    where id = transaction_record.charger_id and status = 'borrowed';
end;
$$;

grant execute on function public.list_admin_users() to anon, authenticated;
grant execute on function public.create_admin_user(text, text) to anon, authenticated;
grant execute on function public.approve_charger_return(bigint, bigint) to anon, authenticated;
notify pgrst, 'reload schema';
commit;
