begin;

create table if not exists public.phones (
    id bigint generated by default as identity primary key,
    phone_identifier text not null unique,
    description text,
    phone_number text not null,
    status text not null default 'available' check (status in ('available', 'borrowed')),
    created_at timestamptz not null default now()
);

create table if not exists public.phone_transactions (
    id bigint generated by default as identity primary key,
    phone_id bigint not null references public.phones(id) on delete restrict,
    borrowed_date date not null,
    borrowed_time time not null,
    borrowed_person text not null,
    department text not null check (department in ('Loading Sector', 'FG Sector', 'RM sector', 'Slitting Sector')),
    returned_date date,
    returned_time time,
    returned_person text,
    returned_by_username text,
    returned_to_admin_id bigint references public.app_users(id) on delete set null,
    approved_by_admin_id bigint references public.admins(id) on delete set null,
    approved_at timestamptz,
    status text not null default 'borrowed' check (status in ('borrowed', 'return_pending', 'returned')),
    created_at timestamptz not null default now()
);

create table if not exists public.phone_damage_reports (
    id bigint generated by default as identity primary key,
    phone_id bigint not null references public.phones(id) on delete restrict,
    damage_description text not null,
    repair_status text not null default 'pending' check (repair_status in ('pending', 'repaired')),
    reported_at timestamptz not null default now(),
    repaired_at timestamptz
);

alter table public.phones enable row level security;
alter table public.phone_transactions enable row level security;
alter table public.phone_damage_reports enable row level security;

drop policy if exists "Allow phone reads" on public.phones;
create policy "Allow phone reads" on public.phones for select using (true);
drop policy if exists "Allow phone inserts" on public.phones;
create policy "Allow phone inserts" on public.phones for insert with check (true);
drop policy if exists "Allow phone updates" on public.phones;
create policy "Allow phone updates" on public.phones for update using (true) with check (true);
drop policy if exists "Allow phone deletes" on public.phones;
create policy "Allow phone deletes" on public.phones for delete using (true);

drop policy if exists "Allow phone transaction reads" on public.phone_transactions;
create policy "Allow phone transaction reads" on public.phone_transactions for select using (true);
drop policy if exists "Allow phone transaction inserts" on public.phone_transactions;
create policy "Allow phone transaction inserts" on public.phone_transactions for insert with check (true);
drop policy if exists "Allow phone transaction updates" on public.phone_transactions;
create policy "Allow phone transaction updates" on public.phone_transactions for update using (true) with check (true);

drop policy if exists "Allow phone damage reads" on public.phone_damage_reports;
create policy "Allow phone damage reads" on public.phone_damage_reports for select using (true);
drop policy if exists "Allow phone damage inserts" on public.phone_damage_reports;
create policy "Allow phone damage inserts" on public.phone_damage_reports for insert with check (true);
drop policy if exists "Allow phone damage updates" on public.phone_damage_reports;
create policy "Allow phone damage updates" on public.phone_damage_reports for update using (true) with check (true);

create or replace function public.borrow_phone(p_phone_id bigint, p_borrowed_date date, p_borrowed_time time, p_borrowed_person text, p_department text)
returns void language plpgsql security definer set search_path = public
as $$
begin
    update public.phones set status = 'borrowed' where id = p_phone_id and status = 'available';
    if not found then raise exception 'This phone is no longer available.'; end if;
    insert into public.phone_transactions(phone_id, borrowed_date, borrowed_time, borrowed_person, department, status)
    values (p_phone_id, p_borrowed_date, p_borrowed_time, trim(p_borrowed_person), p_department, 'borrowed');
end;
$$;

create or replace function public.approve_phone_return(p_transaction_id bigint, p_admin_user_id bigint)
returns void language plpgsql security definer set search_path = public
as $$
declare tx public.phone_transactions; admin_record public.admins;
begin
    select a.* into admin_record from public.admins a join public.app_users u on u.id = a.app_user_id
    where a.app_user_id = p_admin_user_id and u.role = 'admin' and u.is_active = true;
    if admin_record.id is null then raise exception 'Only an active admin can approve returns.'; end if;
    select * into tx from public.phone_transactions where id = p_transaction_id and status = 'return_pending'
      and returned_to_admin_id = p_admin_user_id for update;
    if tx.id is null then raise exception 'This return is not assigned to you or is no longer pending.'; end if;
    update public.phone_transactions set status = 'returned', approved_by_admin_id = admin_record.id, approved_at = now() where id = tx.id;
    update public.phones set status = 'available' where id = tx.phone_id and status = 'borrowed';
end;
$$;

grant execute on function public.borrow_phone(bigint, date, time, text, text) to anon, authenticated;
grant execute on function public.approve_phone_return(bigint, bigint) to anon, authenticated;
notify pgrst, 'reload schema';
commit;
