import { useEffect, useState } from 'react';
import { deletePhone, getAllPhones, updatePhone } from '../../services/phoneService';
import type { Phone } from '../../types/phone';
export default function AvailablePhones({ onBack }: { onBack: () => void }) {
  const [phones, setPhones] = useState<Phone[]>([]); const [editing, setEditing] = useState<number | null>(null);
  const [fields, setFields] = useState({ id: '', description: '', number: '' });
  const load = async () => setPhones((await getAllPhones()).filter(phone => phone.status === 'available'));
  useEffect(() => { void load(); }, []);
  const save = async () => { if (editing === null || !fields.id.trim() || !fields.number.trim()) return; await updatePhone(editing, fields.id, fields.description, fields.number); setEditing(null); await load(); };
  return <div className="app-page"><header className="app-header"><div><h1>MELWIRE LANKA (PVT) LTD</h1><p>PHONE & CHARGER MANAGEMENT SYSTEM</p></div></header><main className="dashboard"><button className="back-button" onClick={onBack}>← Back to Dashboard</button><div className="data-card"><div className="data-card-header"><div><h2>Available Phones</h2><p>Phones available for borrowing.</p></div><span className="count-badge">{phones.length}</span></div>{phones.length === 0 ? <div className="empty-state">No phones are currently available.</div> : <div className="table-wrapper"><table><thead><tr><th>Phone ID</th><th>Description</th><th>Phone No.</th><th>Actions</th></tr></thead><tbody>{phones.map(phone => <tr key={phone.id}>{editing === phone.id ? <><td><input className="table-edit-input" value={fields.id} onChange={e => setFields({ ...fields, id: e.target.value })} /></td><td><input className="table-edit-input" value={fields.description} onChange={e => setFields({ ...fields, description: e.target.value })} /></td><td><input className="table-edit-input" value={fields.number} onChange={e => setFields({ ...fields, number: e.target.value })} /></td><td><button className="primary-button" onClick={() => void save()}>Save</button></td></> : <><td><strong>{phone.phone_identifier}</strong></td><td>{phone.description}</td><td>{phone.phone_number}</td><td><button className="secondary-button" onClick={() => { setEditing(phone.id); setFields({ id: phone.phone_identifier, description: phone.description || '', number: phone.phone_number }); }}>Edit</button>{' '}<button className="secondary-button danger-action" onClick={async () => { if (window.confirm(`Delete ${phone.phone_identifier}?`)) { await deletePhone(phone.id); await load(); } }}>Delete</button></td></>}</tr>)}</tbody></table></div>}</div></main></div>;
}
