import { useEffect, useState } from 'react';
import { getAllPhones } from '../../services/phoneService';
import { addPhoneDamageReport, getPhoneDamageReports, updatePhoneDamageReport, type PhoneDamageReport } from '../../services/phoneDamageService';
import type { Phone } from '../../types/phone';
export default function DamagedPhones({ onBack }: { onBack: () => void }) {
  const [phones, setPhones] = useState<Phone[]>([]); const [reports, setReports] = useState<PhoneDamageReport[]>([]); const [phoneId, setPhoneId] = useState(''); const [description, setDescription] = useState('');
  const load = async () => { const [p, r] = await Promise.all([getAllPhones(), getPhoneDamageReports()]); setPhones(p); setReports(r); }; useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!phoneId || !description.trim()) return; await addPhoneDamageReport(Number(phoneId), description); setPhoneId(''); setDescription(''); await load(); };
  return <div className="app-page"><header className="app-header"><div><h1>MELWIRE LANKA (PVT) LTD</h1><p>PHONE & CHARGER MANAGEMENT SYSTEM</p></div></header><main className="dashboard"><button className="back-button" onClick={onBack}>← Back</button><div className="data-card"><h2>Record Damaged Phone</h2><form onSubmit={submit}><div className="form-row"><div className="form-group"><label>Phone</label><select value={phoneId} onChange={e => setPhoneId(e.target.value)} required><option value="">Select a phone</option>{phones.map(phone => <option key={phone.id} value={phone.id}>{phone.phone_identifier}</option>)}</select></div><div className="form-group"><label>Damage description</label><input value={description} onChange={e => setDescription(e.target.value)} required /></div></div><button className="primary-button">Record Damage</button></form></div><div className="data-card"><h2>Phone Damage Records</h2>{reports.length === 0 ? <div className="empty-state">No phone damage records found.</div> : <div className="table-wrapper"><table><thead><tr><th>Phone</th><th>Damage</th><th>Status</th><th>Action</th></tr></thead><tbody>{reports.map(report => <tr key={report.id}><td>{report.phones?.phone_identifier || `Phone #${report.phone_id}`}</td><td>{report.damage_description}</td><td>{report.repair_status}</td><td><button className="secondary-button" onClick={async () => { await updatePhoneDamageReport(report.id, report.damage_description, report.repair_status === 'repaired' ? 'pending' : 'repaired'); await load(); }}>{report.repair_status === 'repaired' ? 'Needs Repair' : 'Mark Repaired'}</button></td></tr>)}</tbody></table></div>}</div></main></div>;
}
